name: lint
on:
  pull_request:

jobs:
  validate-renovate-config:
    name: validate renovate config
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - name: validate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: ".github/renovate.json"
  eslint:
    name: run eslint, prettier
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: install node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        name: install pnpm
        id: pnpm-install
        with:
          run_install: false
          version: 8

      - name: get cache directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v3.3.1
        name: set up cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install deps
        run: pnpm install

      - name: run eslint
        run: node_modules/.bin/eslint --quiet .

      - name: run pretter
        run: node_modules/.bin/prettier -c .
